language: node_js
node_js:
# - 7 # 7 is not supported by NPM, it will fallback to npm@3, which does not run prepublishOnly hook
  - 8 # 8 is a LTS version with latest NPM packed

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

cache:
  directories:
    - node_modules

after_script:
    - npm run coveralls

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

on:
  branch: master
  tags: true


jobs:
  include:
    - stage: "NPM publish"
      script: skip
      deploy:
        provider: npm
        email: "leishenghao@126.com"
        api_key: $NPM_AUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true

stages:
  - test
  - name: "NPM publish"
    if: tag IS present # only include deploy stage when it's a tagged commit
